### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by tannisroot** [Null-Senpai/discord-wine-dummy#3]
When I try to run `discordcomp.sh` it fails to run and outputs "Permission Denied". Why?
Does it need root permissions? The readme doesn't mention it.
And if it is needed, why?

**Comment by null-von-sushi** [comment]
strange, it should not need root.
Did you make the script executable before running (`chmod +x` or click Enable running as program under 'Permissions' in the nautilus file manager)?

If that still doesn't work, tell me your distribution and I will try to replicate and fix the problem.

**Comment by tannisroot** [comment]
Sorry! Apparently my file manager was borked and wouldn't make it executable through GUI for some reason. Works ok after chmod+x.
